trigger: none

pool: dev-infra-pool

jobs:
- job: TERRAFORM INIT
  displayName: string 
  steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)env/dev'
      backendServiceArm: 'kashi-dev-app'
      backendAzureRmResourceGroupName: 'statefile'
      backendAzureRmStorageAccountName: 'statefile89234'
      backendAzureRmContainerName: 'statefile'
      backendAzureRmKey: 'prod.terraform.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'

jobs: 
 - job: 
   displayName: TERRAFORM PLAN
   steps: 
   - task: TerraformTask@5
     inputs:
       provider: 'azurerm'
       command: 'plan'
       environmentServiceNameAzureRM: 'kashi-dev-app'

