trigger: none

pool: dev-infra-pool

jobs:
- job: TERRAFORM_INIT
  displayName: TERRAFORM_INIT
  steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
# C:\vsts-agent-win-x64-4.261.0\_work\3\s
# C:\vsts-agent-win-x64-4.261.0\_work\3\s\env\dev
# workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      backendServiceArm: 'kashi-dev-app'
      backendAzureRmStorageAccountName: 'devstg72'
      backendAzureRmContainerName: 'devcontainer72'
      backendAzureRmKey: 'terraform.tfstate'