trigger: none

pool: dev-infra-pool

jobs:
- job: TERRAFORM_INIT
  displayName: TERRAFORM_INIT
  steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'


  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      backendServiceArm: 'kashi-dev-app'
      backendAzureRmStorageAccountName: 'devstg72'
      backendAzureRmContainerName: 'devcontainer72'
      backendAzureRmKey: 'terraform.tfstate'

- job: TERRAFORM_PLAN
  displayName: TERRAFORM_PLAN
  steps: 

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      backendServiceArm: 'kashi-dev-app'
      backendAzureRmStorageAccountName: 'devstg72'
      backendAzureRmContainerName: 'devcontainer72'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      environmentServiceNameAzureRM: 'kashi-dev-app'